version: '3.8'

services:
  db:
    container_name: hashesAppContainer
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgresDatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: